name: Calc Helper Continous Integration

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x86, x64]
    runs-on: windows-latest
    env:
      Solution_Path: CalcHelperDesktop.sln
      Test_Project_Path: CalcHelperDesktop.Tests\CalcHelperDesktop.Tests.csproj
      Wpf_Project_Path: CalcHelperDesktop\CalcHelperDesktop.csproj
      Actions_Allow_Unsecure_Commands: true
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install .NetCore
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.302'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Restore application dependencies
      run: msbuild .\CalcHelperDesktop.sln /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
      env:
        Configuration: Release
        RuntimeIdentifier: win-${{ matrix.targetplatform }}
    
    - name: Restore Project
      run: nuget restore $env:Solution_Path
    
    - name: Execute Unit Tests
      run: dotnet test $env:Test_Project_Path
    
    - name: Build Application as single exe
      run: msbuild .\CalcHelperDesktop.sln /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier /p:PublishSingleFile=true /p:UseAppHost=true
      env:
        Configuration: Release
        RuntimeIdentifier: win-${{ matrix.targetplatform }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Exe file
        path: CalcHelperDesktop\bin\Release\app.publish
      
