name: Calc Helper Continous Integration

on:
  push:
    branches-ignore: 
      - main
  pull_request:
    branches-ignore: 
      - main

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x86, x64]
        targetSystem: [win]
    runs-on: windows-latest
    env:
      Solution_Path: CalcHelperDesktop.sln
      Test_Project_Path: CalcHelperDesktop.Tests\CalcHelperDesktop.Tests.csproj
      Wpf_Project_Path: CalcHelperDesktop\CalcHelperDesktop.csproj
      Actions_Allow_Unsecure_Commands: true
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install .NetCore
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.302'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Restore application dependencies
      run: msbuild .\CalcHelperDesktop.sln /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
      env:
        Configuration: Debug
        RuntimeIdentifier: ${{ matrix.targetSystem }}-${{ matrix.targetplatform }}
    
    - name: Execute Unit Tests
      run: dotnet test $env:Test_Project_Path
    
    - name: Build Application as single exe
      run: msbuild .\CalcHelperDesktop.sln /t:CalcHelperDesktop /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier /p:PublishSingleFile=true /p:UseAppHost=true
      env:
        Configuration: Debug
        RuntimeIdentifier: ${{ matrix.targetSystem }}-${{ matrix.targetplatform }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Dev (${{ matrix.targetSystem }}-${{ matrix.targetplatform }})
        path: CalcHelperDesktop\bin\Debug\app.publish
      
